### PR TITLE
LRN-31488 PHP8 Support

### PR DESCRIPTION
**Pull request by rhiannon-eldridge-lrn**
## Checklist

- [X] Feature
- [X] Bug

- [X] ChangeLog.md updated

- [X] Tests added
- [X] All testsuite passes
- [X] `make dist` completed successfully

### CODE REVIEW

**Comment by ttton** [comment]
As part of the test improvements and coverage piece, consider adding tests to cover the scenario fixed in #53.

**Comment by jack-lin-lrn** [comment]
LGTM, start to func

**Review by jack-lin-lrn — APPROVED** [review]
Please rebase and squash if needed, it's good to merge

**Comment by ttton** [comment]
@rhiannon-eldridge-lrn you'll need to update the [changelog](https://github.com/Learnosity/learnosity-sdk-php/blob/master/ChangeLog.md) as well.

**Review by ttton — CHANGES_REQUESTED** [review]
@rhiannon-eldridge-lrn can you update the changelog file?

**Review by jack-lin-lrn — APPROVED** [review]

**Pull request merged**
