### PR TITLE
Bug/dataapi request packet

### PR DESCRIPTION
**Pull request by shtrom**
## Checklist

- [ ] Feature
- [X] Bug

- [X] ChangeLog.md updated

- [ ] Tests added
- [X] All testsuite passes
- [X] `make dist` completed successfully

### CODE REVIEW

**Comment by shtrom** [comment]
@flakeparadigm this should fix the test issue that ran into with your PR; please rebase/merge with this, and all should be fine.

**Comment by shtrom** [comment]
The FIXME is for backward compatibility with existing users. I guess a better way would be to add a warning saying that it should be an array.

**Comment by flakeparadigm** [comment]
A warning might be useful if you have a sec to add it in. I'm not sure that everyone using this will have the time to look through the code changes of every release they update to in order to see the FIXME.

**Comment by shtrom** [comment]
@flakeparadigm  Ready for CR.

**Comment by shtrom** [comment]
Hum, some CBF linting changes snuck in, but they can't hurt.

**Comment by shtrom** [comment]
Agreed, no need for a release just yet.

**Pull request merged**
